base_url = "https://andreagelmi.com"
title = "~/0x41ndrea"
description = "Security Researcher & Penetration Testing"
author = "Andrea Gelmi"
compile_sass = true
minify_html = true
generate_feeds = false
# feed_filenames = ["feed.xml"]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true
unsafe = true

[extra]
github = "https://github.com/ElliotAlderson003"
linkedin = "https://www.linkedin.com/in/andrea-gelmi-727590317/"
email = "gelmi.andrea05@gmail.com@email.com"

# Menu principale
[[extra.menu]]
name = "Posts"
url = "/posts/"
weight = 1

[[extra.menu]]
name = "Writeups"
url = "/writeup/"
weight = 2

[[extra.menu]]
name = "Certifications"
url = "/certifications/"
weight = 3

[[extra.menu]]
name = "About"
url = "/about/"
weight = 4
