base_url = "https://andreag05.github.io/blog"
title = "~/0x41ndrea"
description = "Security Researcher & Penetration Testing"
author = "Andrea Gelmi"
compile_sass = true
minify_html = true
generate_feeds = false

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true
unsafe = true

[extra]
github = "https://github.com/AndreaG05"
linkedin = "https://www.linkedin.com/in/andrea-gelmi-727590317/"
email = "andre.infosec@gmail.com"

# Menu principale
[[extra.menu]]
name = "Posts"
url = "/blog/posts/"
weight = 1

[[extra.menu]]
name = "Writeups"
url = "/blog/writeup/"
weight = 2

[[extra.menu]]
name = "Certifications"
url = "/blog/certifications/"
weight = 3

[[extra.menu]]
name = "About"
url = "/blog/about/"
weight = 4
